### ISSUE TITLE
Issues and fixes

### ISSUE THREAD

**Issue by edannon** [MaxBab/bareos-ansible#3]
- At the README file, please remove "-" from Bareos-basic

- Why do you use template at:
bareos-ansible/roles/bareos-database/tasks/mariadb_install.yml
We could just add repo using their module

- bareos-ansible/roles/bareos-webui/tasks/main.yml
while running flush handlers you are restarting service which does now exists.. why?
I rather getting the name of the app and restart by mentioning the service name "Restart {servicename} service" handler

**Comment by MaxBab** [comment]
* Done.
* Changed to "yum_repository" module.
* Flush handlers execute just the handlers that were previously triggered.
